const express = require('express')
const cors = require('cors')
const authRoutes = require('./routes/auth.routes')
const unidadeRoutes = require('./routes/unidade.routes')
const pedidoRoutes = require('./routes/pedido.routes')
const pontoRoutes = require('./routes/ponto.routes')
const dashboardRoutes = require('./routes/dashboard.routes')
const empresaRoutes = require('./routes/empresa.routes')
const usuarioRoutes = require('./routes/usuario.routes')
const configuracaoRoutes = require('./routes/configuracao.routes')
const folhaRoutes = require('./routes/folha.routes')
const faturamentoRoutes = require('./routes/faturamento.routes')
const linkRoutes = require('./routes/link.routes')
const terceirizadaRoutes = require('./routes/terceirizada.routes')
const { errorHandler } = require('./middleware/errorHandler')

const app = express()

app.use(cors({ origin: '*', credentials: true }))
app.use(express.json({ limit: '10mb' }))
app.use(express.urlencoded({ extended: true, limit: '10mb' }))

app.get('/api/health', (req, res) => res.json({ ok: true }))

app.use('/api/auth', authRoutes)
app.use('/api/unidades', unidadeRoutes)
app.use('/api/pedidos', pedidoRoutes)
app.use('/api/pontos', pontoRoutes)
app.use('/api/dashboard', dashboardRoutes)
app.use('/api/empresas', empresaRoutes)
app.use('/api/usuarios', usuarioRoutes)
app.use('/api/configuracao', configuracaoRoutes)
app.use('/api/folha', folhaRoutes)
app.use('/api/faturamento', faturamentoRoutes)
app.use('/api/links', linkRoutes)
app.use('/api/terceirizadas', terceirizadaRoutes)
app.use(errorHandler)

module.exports = app
